### ISSUE TITLE
Add copy to clipboard button on code snippets

### ISSUE THREAD

**Issue by al-esc** [crowdfavorite/old-crowdfavorite.github.io#30]
Whenever a code snippet is added to a page, it would be great to have a button that allows for copying the code to the clipboard. 

Have not researched this yet, but I am assuming this is a feature already present in the used tech stack

**Comment by nnjeim** [comment]
@al-esc 
https://stackoverflow.com/questions/3582671/how-to-open-a-local-disk-file-with-javascript
copy the php content and place it in a hidden element 
// Copy the text inside the text field
 navigator.clipboard.writeText(ele.value?);

**Comment by al-esc** [comment]
closed by #32
